use super::{BrowserProfile, Http2Profile, Http2StreamDependency, TlsProfile};

pub fn chrome_147() -> BrowserProfile {
    BrowserProfile {
        id: "chrome_147".to_string(),
        browser: "chrome".to_string(),
        version: "147.0.7727.101/102".to_string(),
        platform: "linux".to_string(),
        headers: vec![
            (
                "sec-ch-ua".to_string(),
                "\"Chromium\";v=\"147\", \"Not.A/Brand\";v=\"24\", \"Google Chrome\";v=\"147\""
                    .to_string(),
            ),
            ("sec-ch-ua-mobile".to_string(), "?0".to_string()),
            ("sec-ch-ua-platform".to_string(), "\"Linux\"".to_string()),
            ("upgrade-insecure-requests".to_string(), "1".to_string()),
            (
                "user-agent".to_string(),
                "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36".to_string(),
            ),
            ("accept-language".to_string(), "en-US,en;q=0.9".to_string()),
            (
                "accept".to_string(),
                "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7".to_string(),
            ),
            ("sec-fetch-site".to_string(), "none".to_string()),
            ("sec-fetch-mode".to_string(), "navigate".to_string()),
            ("sec-fetch-user".to_string(), "?1".to_string()),
            ("sec-fetch-dest".to_string(), "document".to_string()),
            (
                "accept-encoding".to_string(),
                "gzip, deflate, br, zstd".to_string(),
            ),
            ("priority".to_string(), "u=0, i".to_string()),
        ],
        tls: TlsProfile {
            alpn: vec!["h2".to_string(), "http/1.1".to_string()],
            alps: vec![],
            alps_use_new_codepoint: false,
            certificate_compression: vec!["brotli".to_string()],
            curves: vec![
                "X25519MLKEM768".to_string(),
                "X25519".to_string(),
                "P-256".to_string(),
                "P-384".to_string(),
                "P-521".to_string(),
                "ffdhe2048".to_string(),
                "ffdhe3072".to_string(),
            ],
            cipher_suites: vec![
                "TLS_AES_128_GCM_SHA256".to_string(),
                "TLS_CHACHA20_POLY1305_SHA256".to_string(),
                "TLS_AES_256_GCM_SHA384".to_string(),
                "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256".to_string(),
                "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256".to_string(),
                "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256".to_string(),
                "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256".to_string(),
                "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384".to_string(),
                "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384".to_string(),
                "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA".to_string(),
                "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA".to_string(),
                "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA".to_string(),
                "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA".to_string(),
                "TLS_RSA_WITH_AES_128_GCM_SHA256".to_string(),
                "TLS_RSA_WITH_AES_256_GCM_SHA384".to_string(),
                "TLS_RSA_WITH_AES_128_CBC_SHA".to_string(),
                "TLS_RSA_WITH_AES_256_CBC_SHA".to_string(),
            ],
            delegated_credentials: vec![
                "ecdsa_secp256r1_sha256".to_string(),
                "ecdsa_secp384r1_sha384".to_string(),
                "ecdsa_secp521r1_sha512".to_string(),
                "ecdsa_sha1".to_string(),
            ],
            signature_algorithms: vec![
                "ecdsa_secp256r1_sha256".to_string(),
                "ecdsa_secp384r1_sha384".to_string(),
                "ecdsa_secp521r1_sha512".to_string(),
                "rsa_pss_rsae_sha256".to_string(),
                "rsa_pss_rsae_sha384".to_string(),
                "rsa_pss_rsae_sha512".to_string(),
                "rsa_pkcs1_sha256".to_string(),
                "rsa_pkcs1_sha384".to_string(),
                "rsa_pkcs1_sha512".to_string(),
                "ecdsa_sha1".to_string(),
                "rsa_pkcs1_sha1".to_string(),
            ],
            key_share_groups: vec![
                "X25519MLKEM768".to_string(),
                "X25519".to_string(),
                "P-256".to_string(),
            ],
            extension_order: vec![
                "server_name".to_string(),
                "extended_master_secret".to_string(),
                "renegotiate".to_string(),
                "supported_groups".to_string(),
                "ec_point_formats".to_string(),
                "session_ticket".to_string(),
                "application_layer_protocol_negotiation".to_string(),
                "status_request".to_string(),
                "delegated_credential".to_string(),
                "certificate_timestamp".to_string(),
                "key_share".to_string(),
                "supported_versions".to_string(),
                "signature_algorithms".to_string(),
                "psk_key_exchange_modes".to_string(),
                "record_size_limit".to_string(),
                "cert_compression".to_string(),
                "encrypted_client_hello".to_string(),
                "padding".to_string(),
            ],
            min_version: "tls1.2".to_string(),
            max_version: "tls1.3".to_string(),
            record_size_limit: Some(0x4001),
            ech_grease: true,
            extension_permutation: true,
            grease_enabled: None,
            pre_shared_key: true,
            preserve_tls13_cipher_list: true,
            ocsp_stapling: true,
            signed_cert_timestamps: true,
            notes: "Chrome 147 template backed by BoringSSL-style TLS options. Replace values from fresh capture when Chrome 148 ships.".to_string(),
        },
        http2: Http2Profile {
            pseudo_header_order: vec![
                ":method".to_string(),
                ":path".to_string(),
                ":authority".to_string(),
                ":scheme".to_string(),
            ],
            settings_order: vec![
                "header_table_size".to_string(),
                "enable_push".to_string(),
                "max_concurrent_streams".to_string(),
                "initial_window_size".to_string(),
                "max_frame_size".to_string(),
                "max_header_list_size".to_string(),
                "enable_connect_protocol".to_string(),
                "no_rfc7540_priorities".to_string(),
            ],
            settings: vec![
                ("header_table_size".to_string(), 65536),
                ("enable_push".to_string(), 0),
                ("initial_window_size".to_string(), 131072),
                ("max_frame_size".to_string(), 16384),
            ],
            initial_stream_id: Some(3),
            initial_connection_window_size: Some(12_582_912),
            stream_dependency: Some(Http2StreamDependency {
                stream_id: 0,
                weight: 41,
                exclusive: false,
            }),
            priority_header: Some("u=0, i".to_string()),
        },
    }
}
